// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_usage.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createAIUsage = `-- name: CreateAIUsage :one
INSERT INTO ai_usage (
    user_id,
    inspection_id,
    model,
    input_tokens,
    output_tokens,
    cost_cents,
    request_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, inspection_id, model, input_tokens, output_tokens, cost_cents, request_type, created_at
`

type CreateAIUsageParams struct {
	UserID       uuid.UUID     `json:"user_id"`
	InspectionID uuid.NullUUID `json:"inspection_id"`
	Model        string        `json:"model"`
	InputTokens  int32         `json:"input_tokens"`
	OutputTokens int32         `json:"output_tokens"`
	CostCents    int32         `json:"cost_cents"`
	RequestType  string        `json:"request_type"`
}

func (q *Queries) CreateAIUsage(ctx context.Context, arg CreateAIUsageParams) (AiUsage, error) {
	row := q.db.QueryRowContext(ctx, createAIUsage,
		arg.UserID,
		arg.InspectionID,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostCents,
		arg.RequestType,
	)
	var i AiUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InspectionID,
		&i.Model,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostCents,
		&i.RequestType,
		&i.CreatedAt,
	)
	return i, err
}

const getUserAIUsageThisMonth = `-- name: GetUserAIUsageThisMonth :one
SELECT
    COALESCE(SUM(input_tokens), 0) as total_input_tokens,
    COALESCE(SUM(output_tokens), 0) as total_output_tokens,
    COALESCE(SUM(cost_cents), 0) as total_cost_cents,
    COUNT(*) as request_count
FROM ai_usage
WHERE user_id = $1
AND created_at >= date_trunc('month', NOW())
AND created_at < date_trunc('month', NOW()) + INTERVAL '1 month'
`

type GetUserAIUsageThisMonthRow struct {
	TotalInputTokens  interface{} `json:"total_input_tokens"`
	TotalOutputTokens interface{} `json:"total_output_tokens"`
	TotalCostCents    interface{} `json:"total_cost_cents"`
	RequestCount      int64       `json:"request_count"`
}

func (q *Queries) GetUserAIUsageThisMonth(ctx context.Context, userID uuid.UUID) (GetUserAIUsageThisMonthRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAIUsageThisMonth, userID)
	var i GetUserAIUsageThisMonthRow
	err := row.Scan(
		&i.TotalInputTokens,
		&i.TotalOutputTokens,
		&i.TotalCostCents,
		&i.RequestCount,
	)
	return i, err
}
