// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countReportsByUserID = `-- name: CountReportsByUserID :one
SELECT COUNT(*) FROM reports
WHERE user_id = $1
`

func (q *Queries) CountReportsByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReportsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReportsThisMonthByUserID = `-- name: CountReportsThisMonthByUserID :one
SELECT COUNT(*) FROM reports
WHERE user_id = $1
  AND generated_at >= DATE_TRUNC('month', CURRENT_TIMESTAMP)
`

func (q *Queries) CountReportsThisMonthByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReportsThisMonthByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    inspection_id,
    user_id,
    pdf_storage_key,
    docx_storage_key,
    violation_count
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, inspection_id, user_id, pdf_storage_key, docx_storage_key, violation_count, generated_at
`

type CreateReportParams struct {
	InspectionID   uuid.UUID      `json:"inspection_id"`
	UserID         uuid.UUID      `json:"user_id"`
	PdfStorageKey  sql.NullString `json:"pdf_storage_key"`
	DocxStorageKey sql.NullString `json:"docx_storage_key"`
	ViolationCount int32          `json:"violation_count"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, createReport,
		arg.InspectionID,
		arg.UserID,
		arg.PdfStorageKey,
		arg.DocxStorageKey,
		arg.ViolationCount,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.InspectionID,
		&i.UserID,
		&i.PdfStorageKey,
		&i.DocxStorageKey,
		&i.ViolationCount,
		&i.GeneratedAt,
	)
	return i, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, inspection_id, user_id, pdf_storage_key, docx_storage_key, violation_count, generated_at FROM reports
WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id uuid.UUID) (Report, error) {
	row := q.db.QueryRowContext(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.InspectionID,
		&i.UserID,
		&i.PdfStorageKey,
		&i.DocxStorageKey,
		&i.ViolationCount,
		&i.GeneratedAt,
	)
	return i, err
}

const getReportByIDAndUserID = `-- name: GetReportByIDAndUserID :one
SELECT id, inspection_id, user_id, pdf_storage_key, docx_storage_key, violation_count, generated_at FROM reports
WHERE id = $1 AND user_id = $2
`

type GetReportByIDAndUserIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetReportByIDAndUserID(ctx context.Context, arg GetReportByIDAndUserIDParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, getReportByIDAndUserID, arg.ID, arg.UserID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.InspectionID,
		&i.UserID,
		&i.PdfStorageKey,
		&i.DocxStorageKey,
		&i.ViolationCount,
		&i.GeneratedAt,
	)
	return i, err
}

const listReportsByInspectionID = `-- name: ListReportsByInspectionID :many
SELECT id, inspection_id, user_id, pdf_storage_key, docx_storage_key, violation_count, generated_at FROM reports
WHERE inspection_id = $1
ORDER BY generated_at DESC
`

func (q *Queries) ListReportsByInspectionID(ctx context.Context, inspectionID uuid.UUID) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listReportsByInspectionID, inspectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.InspectionID,
			&i.UserID,
			&i.PdfStorageKey,
			&i.DocxStorageKey,
			&i.ViolationCount,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
