// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password_hash,
    name,
    company_name,
    phone
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, email, password_hash, name, company_name, phone, stripe_customer_id, subscription_status, subscription_tier, subscription_id, email_verified, email_verified_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Name         string         `json:"name"`
	CompanyName  sql.NullString `json:"company_name"`
	Phone        sql.NullString `json:"phone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.CompanyName,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CompanyName,
		&i.Phone,
		&i.StripeCustomerID,
		&i.SubscriptionStatus,
		&i.SubscriptionTier,
		&i.SubscriptionID,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, company_name, phone, stripe_customer_id, subscription_status, subscription_tier, subscription_id, email_verified, email_verified_at, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CompanyName,
		&i.Phone,
		&i.StripeCustomerID,
		&i.SubscriptionStatus,
		&i.SubscriptionTier,
		&i.SubscriptionID,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, company_name, phone, stripe_customer_id, subscription_status, subscription_tier, subscription_id, email_verified, email_verified_at, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CompanyName,
		&i.Phone,
		&i.StripeCustomerID,
		&i.SubscriptionStatus,
		&i.SubscriptionTier,
		&i.SubscriptionID,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByStripeCustomerID = `-- name: GetUserByStripeCustomerID :one
SELECT id, email, password_hash, name, company_name, phone, stripe_customer_id, subscription_status, subscription_tier, subscription_id, email_verified, email_verified_at, created_at, updated_at FROM users
WHERE stripe_customer_id = $1
`

func (q *Queries) GetUserByStripeCustomerID(ctx context.Context, stripeCustomerID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByStripeCustomerID, stripeCustomerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CompanyName,
		&i.Phone,
		&i.StripeCustomerID,
		&i.SubscriptionStatus,
		&i.SubscriptionTier,
		&i.SubscriptionID,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEmailVerification = `-- name: UpdateUserEmailVerification :exec
UPDATE users
SET email_verified = $2,
    email_verified_at = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserEmailVerificationParams struct {
	ID              uuid.UUID    `json:"id"`
	EmailVerified   sql.NullBool `json:"email_verified"`
	EmailVerifiedAt sql.NullTime `json:"email_verified_at"`
}

func (q *Queries) UpdateUserEmailVerification(ctx context.Context, arg UpdateUserEmailVerificationParams) error {
	_, err := q.db.ExecContext(ctx, updateUserEmailVerification, arg.ID, arg.EmailVerified, arg.EmailVerifiedAt)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET name = $2,
    company_name = $3,
    phone = $4,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	CompanyName sql.NullString `json:"company_name"`
	Phone       sql.NullString `json:"phone"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.CompanyName,
		arg.Phone,
	)
	return err
}

const updateUserStripeCustomer = `-- name: UpdateUserStripeCustomer :exec
UPDATE users
SET stripe_customer_id = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserStripeCustomerParams struct {
	ID               uuid.UUID      `json:"id"`
	StripeCustomerID sql.NullString `json:"stripe_customer_id"`
}

func (q *Queries) UpdateUserStripeCustomer(ctx context.Context, arg UpdateUserStripeCustomerParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStripeCustomer, arg.ID, arg.StripeCustomerID)
	return err
}

const updateUserSubscription = `-- name: UpdateUserSubscription :exec
UPDATE users
SET subscription_status = $2,
    subscription_tier = $3,
    subscription_id = $4,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserSubscriptionParams struct {
	ID                 uuid.UUID      `json:"id"`
	SubscriptionStatus sql.NullString `json:"subscription_status"`
	SubscriptionTier   sql.NullString `json:"subscription_tier"`
	SubscriptionID     sql.NullString `json:"subscription_id"`
}

func (q *Queries) UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSubscription,
		arg.ID,
		arg.SubscriptionStatus,
		arg.SubscriptionTier,
		arg.SubscriptionID,
	)
	return err
}
